# Generated by Django 4.0.4 on 2022-05-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_alcoholic', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('instructions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_alcoholic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(blank=True, max_length=50)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='CocktaildbApp.drink')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='CocktaildbApp.ingredient')),
            ],
            options={
                'unique_together': {('drink', 'ingredient')},
            },
        ),
    ]
