# Generated by Django 4.0.4 on 2022-05-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CocktailApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='PhotoFileName',
        ),
        migrations.AddField(
            model_name='cocktails',
            name='PhotoFileName',
            field=models.CharField(default='ImageNotFound.jpg', max_length=100),
        ),
    ]
